Fix ProtBert tensors stored on different devices
Error: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)"
I think this is due to the input tensor from the tokenizer being stored
on the CPU.