Cache prot bert tokenizer and model separately
Streamlit complaint because it doesn't like caching things
from different devices.
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)